# Generated by Django 4.1.4 on 2022-12-16 12:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
